[[constraint]]
  branch = "master"
  name = "github.com/fluent/fluent-bit-go"

[[constraint]]
  branch = "master"
  name = "github.com/gomodule/redigo"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true
