[[constraint]]
  branch = "master"
  name = "github.com/fluent/fluent-bit-go"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.0.5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
